name: Update Premier League Standings

on:
  schedule:
    # 毎日23:00 (UTC) に実行 (日本時間の午前8時)
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin

      # ▼▼▼ ここが新しい部分です ▼▼▼
      - name: Create Firebase credentials file using Python
        env:
          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
        run: |
          import json
          # シークレットから改行の問題がある文字列を取得
          creds_str_with_newlines = '''${{ env.FIREBASE_CREDENTIALS_JSON }}'''
          # Pythonのjsonライブラリで正しく解釈
          creds_dict = json.loads(creds_str_with_newlines)
          # 正しい形式でファイルに書き出す
          with open('predictionprediction-firebase-adminsdk-fbsvc-e801e9cb8b.json', 'w') as f:
              json.dump(creds_dict, f)

      - name: Run Scraper
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: python scraper.py
