name: Update Premier League Standings

on:
  schedule:
    # 毎日23:00 (UTC) に実行 (日本時間の午前8時)
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests firebase-admin

      - name: Create Firebase credentials file
        run: echo "${{ secrets.FIREBASE_CREDENTIALS_JSON }}" > predictionprediction-firebase-adminsdk-fbsvc-e801e9cb8b.json

      - name: Run Scraper
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: python scraper.py
