# .github/workflows/update_standings.yml

name: Update Premier League Standings

on:
  # 毎日午前5時 (UTC) に自動実行
  schedule:
    - cron: '0 5 * * *'
  # 手動でも実行できるようにする
  workflow_dispatch:

jobs:
  update-standings:
    runs-on: ubuntu-latest
    
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 必要なライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin

      # 4. Pythonスクリプトを実行
      - name: Run update script
        # ここでRepository secretsを環境変数としてスクリプトに渡す
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: python your_script_name.py # ← your_script_name.py は実際のファイル名に書き換えてください
