name: Firebase Connection Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install firebase-admin

      - name: Create Firebase credentials file
        run: echo "${{ secrets.FIREBASE_CREDENTIALS }}" > predictionprediction-firebase-adminsdk-fbsvc-e801e9cb8b.json

      - name: Run Firebase Test Script
        run: python scraper.py
